FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libsndfile1 sox \
 && rm -rf /var/lib/apt/lists/*

COPY requirements_docker.txt .
RUN pip install --no-cache-dir -r requirements_docker.txt

COPY src ./src
COPY assets ./assets
