COMMANDS = ["right", "stop", "up", "go"]

SAMPLE_RATE = 16000
CLIP_SECONDS = 1.0
CLIP_SAMPLES = int(SAMPLE_RATE * CLIP_SECONDS)

N_MELS = 64
BATCH_SIZE_DEFAULT = 32
EPOCHS_DEFAULT = 5
LR_DEFAULT = 1e-3
SEED = 42
